apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dmessagecore-server
  labels:
    app: dmessagecore-server
spec:
  selector:
    matchLabels:
      app: dmessagecore-server
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: dmessagecore-server
        tier: backend
    spec:
      containers:
      - name: dmessagecore-server
        image: #{IMAGETAG-Server}#
      imagePullSecrets:
      - name: regsecret
        ports:
        - containerPort: 8080
          name: dmessagecore-server
        volumeMounts:
        - mountPath: "/var/lib/dmessagecore-server"
          name: dmessagecore-server